fntechgit/summit-registration-lite

src/components/ticket-type/index.js
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=3245309&fileview=grid
=> Fix ticket type warning

.npmignore, README.md, src/components/purchase-complete/index.js, src/components/registration-lite.js, src/i18n/en.json, src/index.js
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=3297179&fileview=grid
Signed-off-by: Tomás Castillo [tcastilloboireau@gmail.com](mailto:tcastilloboireau@gmail.com)
=> Add new settings to customize the purchase complete screen

src/actions.js, src/components/registration-lite.js
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=3314193&stafilter=NotComplete&fileview=grid
=> Unify useEffect, change type/taxes function

src/components/registration-lite.js
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=3314591&stafilter=NotComplete&fileview=grid
=> Move reserve function from hook to prop callback

src/components/purchase-complete/index.js, src/utils/utils.js
* Avoid to display empty string as resources
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3354072
=> Change evaluation of marketing resources

src/components/registration-lite.js
ref: https://tipit.avaza.com/project/view/332800#!tab=task-pane&task=3362428
=> Remove active reservation if widget closes

README.md, src/components/personal-information/__tests__/personal-information.test.js, src/components/personal-information/index.js, src/components/registration-lite.js, src/index.js
ref: https://tipit.avaza.com/project/view/334369#!tab=task-pane&task=3362188
=> Remove input company placeholder

src/components/personal-information/index.js
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=3400333&stafilter=NotComplete&fileview=grid
=> Disable edit on first and last name if they're populated on profile

src/components/personal-information/index.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3398451
=> Adjust styles on company placeholder for longer texts

README.md, src/actions.js, src/components/personal-information/index.js, src/components/personal-information/index.module.scss, src/components/purchase-complete/index.js, src/i18n/en.json, src/index.js, src/summit-registration-lite.js, src/utils/constants.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3417647
=> New Purchase Flow - MySelf / SomeOne else

src/components/ticket-dropdown/index.js, src/components/ticket-type/index.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3428602
=> Add taxes on ticket dropdown

src/components/ticket-dropdown/index.js, src/components/ticket-type/index.js, src/utils/utils.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3428602
=> Add missing taxes ticket type component

package.json, src/components/login/index.js, src/components/login/index.module.scss, src/components/registration-lite.js, yarn.lock
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3408514&stafilter=NotComplete&fileview=grid
=> update login button on login modal

src/components/personal-information/index.js
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3436989&stafilter=NotComplete&fileview=grid
=> Reg Lite: move email input in Someone Else selection after First and last name

src/components/personal-information/index.js
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3438888&stafilter=NotComplete&fileview=grid
=> Reg Lite: fix required error message on Someone Else's email

src/actions.js, src/components/personal-information/index.js, src/components/promocode-input/index.js, src/components/registration-lite.js, src/components/ticket-dropdown/index.js, src/components/ticket-type/index.js, src/helpers/getTicketMaxQuantity.js, src/reducer.js, src/utils/constants.js, src/utils/payment-providers/stripe-provider.js, src/utils/utils.js
chore: refactor and simplyfy logic on reducer
chore: update pre paid logic
=> fix: render logic of ticket types component

src/utils/utils.js
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=3489708&stafilter=NotComplete&fileview=grid
=> Change validations for hasDiscountApplied function

src/components/purchase-complete/index.module.scss, src/index.ejs
https://tipit.avaza.com/project/view/347916#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3498963&stafilter=NotComplete&fileview=grid
=> add marketing color settings to purchase complete button

src/components/ticket-dropdown/index.module.scss
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3500826&stafilter=NotComplete&fileview=grid
=> Remove color_primary from select dropdown

src/components/registration-lite.js, src/reducer.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3513910
=> Move allowed ticket types to reducer, change validation

README.md, src/components/login-passwordless/index.js, src/components/registration-lite.js
ref: https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=3540698
=> Rename props, add proptypes and values, new alt prop

src/components/promocode-input/index.module.scss
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3547233
=> Adjusting styles in mobile view for input and apply discount component

src/components/ticket-dropdown/index.module.scss
https://tipit.avaza.com/project/view/359044#!tab=task-pane&task=3559346
=> change ticket dropdown background and border color settings

src/components/registration-lite.js
https://tipit.avaza.com/project/view/359044#!tab=task-pane&task=3559348
=> add logic for owned tickets message

src/actions.js, src/components/button-bar/index.js, src/components/promocode-input/index.js, src/components/registration-lite.js, src/components/ticket-type/index.js, src/reducer.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3542826
=> Add warning if the promo code is not applied

src/actions.js
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3564979
=> Fix ticket assign reload on summit updates

src/components/stripe-form/index.js, src/components/stripe-form/index.module.scss
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3564351
=> fix: Apply styles on browser autocomplete

src/components/ticket-dropdown/index.js
ref: https://tipit.avaza.com/project/view#!tab=task-pane&task=3572106
=> Prevent DDL to close if summit data is updated

src/components/registration-lite.js, src/components/ticket-type/index.js
ref: https://tipit.avaza.com/project/view#!tab=task-pane&task=3613739&fileview=grid
=> Add ticket type to DDL if prepaid
